spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycorpbio?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: maniraj
    password: Alliswell@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true

  mvc:
    log-request-details: true

#  security:
#    user:
#      name: maniraj
#      password: Alliswell@1


#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 200MB
#      max-request-size: 215MB
server:
  port: 8090


application:
  name: userPostManagement

logging:
  level:
    web: DEBUG
#    org:
#      springframework:
#        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"